### ISSUE TITLE
4.0 Class structure

### ISSUE THREAD

**Issue by flangfeldt** [neverwoods/validformbuilder#20]
### Inheritance schema
- Form _has_ `Collection`
- Wizard
- BaseElement _has `Condition`, `Comparison`_
  - BaseField _has_ `FieldValidator`
    - FormField
    - InputText
    - InputPassword
    - InputFile
    - InputHidden
    - TextArea
    - SelectList
      - ListItemGroup _has_ `Collection`
        - ListItem
      - ListItem
    - CheckList
      - ListItem
    - RadioList
      - ListItem
  - GroupElement _has_ `Collection`
    - FieldSet
    - MultiField
    - Page
  - Element
    - Paragraph
    - Button
    - String 
- Validator

**Comment by rvanbaalen** [comment]
This is implemented in the current version.
