### ISSUE TITLE
JS error on VFORM_BOOLEAN on submit

### ISSUE THREAD

**Issue by Austinb** [neverwoods/validformbuilder#27]
For my form when I add a VFORM_BOOLEAN type field and it is selected I get the following JS error

``` js
TypeError: ValidForm.inArray is not a function
```

Area in question is line 1681 in validform.js

``` js
if (!ValidForm.inArray(this.check, objValidElements.get(intCount))) {
```

This error also prevents the form from being submitted.

**Comment by rvanbaalen** [comment]
Can't reproduce this issue in the current stable release.
