### ISSUE TITLE
VFORM_STRING and VFORM_TEXT fail server side on strings with uppercase Umlauts

### ISSUE THREAD

**Issue by moritzjacobs** [neverwoods/validformbuilder#32]
The String "Österreich" (german name for Austria) validates on client side (JS) but not when submitted to php. I guess the `/i` regex modifier in php does not acknowledge "Ö" being an uppercase "ö". JS does.

I'm not sure how this affects other language's letters like "À" or "Ç"... I found, that adding `/u`as a modifier to the regex seems to do the trick but might raise security concerns? What do you think?

`p{L}` [might also be a solution](https://stackoverflow.com/questions/280712/javascript-unicode-regexes) but also seems only to work with `u` as a modifier, if I'm not mistaken.

Also, having certain typographic characters like em dashes or curly quotes successfully validate would be nice... Any ideas?

**Comment by rvanbaalen** [comment]
@moritzjacobs This seems to be fixed in the latest version of ValidForm Builder. Can you confirm?
