### ISSUE TITLE
Fieldset::setLabelMeta doesn't seem to take effect

### ISSUE THREAD

**Issue by Austinb** [neverwoods/validformbuilder#33]
I am trying to use the setLabelMeta (http://validformbuilder.org/docs/classes/ValidFormBuilder.Fieldset.html) to add a class to all of my labels underneath a specific field set.  It appears that the labels just ignore any of the meta set when being generated.

```php
$fs = $form->addFieldset('name');
$fs->setLabelMeta('class', 'inline');
```
But when the form is generated the only part of the label  is the "for" property.  Am I using this function wrong or is this a bug?  I want to be able to add a class to the labels for checkboxes in a specific fieldset so they line up properly in the form.

**Comment by rvanbaalen** [comment]
VFB has indeed no way to automatically set `label meta` on all child inputs. You could however easily do so by using a `foreach` and looping through the `getFields()` result.
