### ISSUE TITLE
A form with a required VFORM_FILE does never validate.

### ISSUE THREAD

**Issue by tobltobs** [neverwoods/validformbuilder#35]
See https://code.google.com/p/validformbuilder/issues/detail?id=8

It seems this is still not fixed in 3.2

**Comment by rvanbaalen** [comment]
@tobltobs Can you reproduce this with the latest version? For the sake of cleaning up, I'm closing this issue for now but feel free to reopen it and post a code example that replicates this issue if this problem still exists.
