### ISSUE TITLE
No Client side validation for VFORM_INTEGER fields

### ISSUE THREAD

**Issue by tobltobs** [neverwoods/validformbuilder#36]
If a not number is entered into a VFORM_INTEGER field, there seems to be no client side check for the right input type.

**Comment by paulbrab** [comment]
I'm having this issue also. Does anyone have a working example of a VFORM_INTEGER or VFORM_NUMERIC?

Or is it possible to change the input types to 'number' instead of 'text'.

Thanks.

**Comment by rvanbaalen** [comment]
This seems to be fixed in the latest version. Just created a numeric field like this:

```php
/** @var ValidForm $form */
$form = new ValidForm('formName');
$form->addField(
    'numericValue', 
    'Numeric value', 
    ValidForm::VFORM_NUMERIC, 
    ['required' => true], 
    [
        'type' => 'Should be numeric', 
        'required' => 'Required field'
    ]
);
```

and it had perfectly good client-side validation.
