### ISSUE TITLE
Exhausted memory when "circular" conditions

### ISSUE THREAD

**Issue by dynamodan** [neverwoods/validformbuilder#43]
If you make two required fields each have a condition ["required", false] of the other being ValidForm::VFORM_COMPARISON_NOT_EMPTY, you get a memory exhausted error, I presume because of an endless loop cause by being circular.

**Comment by rvanbaalen** [comment]
Yes, if you circle around when linking conditions, this can happen. With great power comes great responsibility and thus it's up to the developer to not create infinite loops like this :-)
