### ISSUE TITLE
PHP errors from install of Nightly and Beta releases

### ISSUE THREAD

**Issue by treffynnon** [neverwoods/validformbuilder#5]
Issue 59 ported from Google Code: https://code.google.com/p/validformbuilder/issues/detail?id=59

---

Error from the nightly and beta release on PHP 5.4.14:
- Declaration of VF_Fieldset::toJS() should be compatible with VF_Base::toJS($intDynamicPosition = 0)
- Declaration of VF_String::getData() should be compatible with VF_Base::getData($strKey = NULL)
- Declaration of VF_Element::toJS() should be compatible with VF_Base::toJS($intDynamicPosition = 0)
- Declaration of VF_Checkbox::toJS() should be compatible with VF_Base::toJS($intDynamicPosition = 0)
- Declaration of VF_SelectOption::toHtml() should be compatible with VF_Element::toHtml($submitted = false, $blnSimpleLayout = false, $blnLabel = true, $blnDisplayErrors = true)

I have stopped here as this last error seems to be a complete API mismatch.

**Comment by rvanbaalen** [comment]
This is fixed in the current version.
