### ISSUE TITLE
Calling ValidWizard::getPage() breaks the form

### ISSUE THREAD

**Issue by kaphert** [neverwoods/validformbuilder#50]
Calling `ValidWizard::getPage($index)` breaks the form. The form is empty after calling this method. The source of the page contains the javascript of the form with the correct addField, addPage methods, etc.. But there are no html form fields. 

It has something to do with the `isSeek = true` parameter in `Collection::seek()`. If I remove this parameter it works fine. I don't know what the purpose is of this parameter but it looks like when the parameter is set it will never be unset. 

```php
$form = new ValidWizard(
    "form",
    null,
    "url"
);

$form->setSubmitLabel("Submit");
$form->addPage('x','xxx');

// comment this line to get result
$objPage = $form->getPage(0);

$form->addField(
    "field",
    "field label",
    ValidForm::VFORM_STRING
);

if ($form->isSubmitted() && $form->isValid()) {
    echo $form->valuesAsHtml();
    echo '<a href="/" />RELOAD</a>';
} else {
    echo $form->toHtml();
}
```

**Comment by rvanbaalen** [comment]
@flangfeldt Wrote the `Collection` class. Perhaps he can shed some light on it?

**Comment by rvanbaalen** [comment]
@kaphert Can you provide a code snippet in which context you use `ValidWizard::getPage()`?

**Comment by kaphert** [comment]
@rvanbaalen  see my updated question. If you load this in the validform playground you won't see the form. If you comment the line `$objPage = $form->getPage(0);` it will show the form

**Comment by flangfeldt** [comment]
The `isSeek` property is used to stop the internal pointer from being rewound by the `foreach` construct. 

The problem lies in the `getPage` method. It is taking the index argument and subtracts 1 regardless of the input value.

```
public function getPage($intIndex = 0)
    {
        $intIndex --; // Convert page no. to index no.
        $this->__elements->seek($intIndex);
```

With an input value of 0 it is sending -1 to the seek method. There will never be a page at position -1 in the Collection.

We need add a better test for the $intIndex variable to insure that it is never less than 0.

**Comment by rvanbaalen** [comment]
See my PR. 

```php
    public function getPage($intIndex = 0)
    {
        $intIndex --; // Convert page no. to index no.
        if ($intIndex < 0) {
            $intIndex = 0;
        }
```

should do the trick
