### ISSUE TITLE
Bug: Since v4.1.2 valuesAsHtml is not correct for dynamic areas

### ISSUE THREAD

**Issue by kaphert** [neverwoods/validformbuilder#55]
Since release 4.1.2 the valuesAsHtml() is not correct for dynamic areas. Only the first dynamic area is showing in the html table generated by valuesAsHtml. All other dynamic areas are being ignored. 

Commit https://github.com/neverwoods/validformbuilder/commit/cb14cf1c784a33ca9496d814f44d5e17b8054251 in 4.1.2 is the issue. If I set the `$blnShouldDisplay` to true everything works.

**Comment by rvanbaalen** [comment]
Confirmed in ValidForm Builder playground sandbox.

**Comment by rvanbaalen** [comment]
I think that we should skip the dynamic counter check in the `elementShouldDisplay` method

https://github.com/neverwoods/validformbuilder/blob/master/classes/ValidFormBuilder/ValidForm.php#L1856

If the condition is met for `dynamicCounter 0`, it applies to all it's dynamic clones as well.
