### ISSUE TITLE
Feature request - Option to get value labels instead of values in valuesAsHtml()

### ISSUE THREAD

**Issue by kaphert** [neverwoods/validformbuilder#64]
If you have a form and you call valuesAsHtml() it will return a html table with all the values. But these values are the real values. In the case you have checkboxes, selects and or radio buttons most of the time the value is something like an id. In these cases it would be nice if the label was shown in this overview instead of the 'real' value.

**Comment by flangfeldt** [comment]
I feel that this request is beyond the scope of the valuesAsHtml method. If you want to spice up the output you can extend the ValidForm class and implement your own logic. The basic implementation was always meant to be a quick and dirty way to show submitted values.

What do you think @rvanbaalen?

**Comment by rvanbaalen** [comment]
I agree that this is easily achievable by extending the ValidForm library. If we would implement this feature, it wouldn't be for just checkboxes / radio buttons but would need to be implemented for all field types
