### ISSUE TITLE
JS validation with two forms and identical field names shows error on wrong form

### ISSUE THREAD

**Issue by kaphert** [neverwoods/validformbuilder#83]
### Expected behavior

It should not be a problem to have multiple forms with the same field name. 

### Actual behavior

I have two forms with identical field names. In form B a field is required. If you leave the field in Form B empty and press submit the field in Form A is highlighted as invalid. 

It looks like it searches for the first form field in the dom. But it should search for the first form field within the form. 

### Steps to reproduce the behavior and a code example

```php
$formA = new ValidForm("formA");
$formA->addField('required', 'Required', ValidForm::VFORM_STRING,
    ['required' => true],
    [],
    ['default' => '']
);

$formB = new ValidForm("formB");
$formB->addField('required', 'Required', ValidForm::VFORM_STRING,
    ['required' => true],
    [],
    ['default' => '']
);

if ($formA->isSubmitted() && $formA->isValid()) {
    echo $formA->valuesAsHtml();
} else {
    echo '<h2>Form A</h2>';
    echo $formA->toHtml();
    echo '<h2>Form B</h2>';
    echo $formB->toHtml();
}

```

### Which version/branch of ValidForm Builder do you use?

Both 4.1.8 and 4.2.0 have this problem

**Comment by rvanbaalen** [comment]
This is expected behaviour. According to HTML standards, 1 page should not contain two elements (in this case form fields) with identical IDs.

**Comment by kaphert** [comment]
That is correct if we are talking about id's. But not about form elements. It is allowed to have form elements with the same name. 

I understand that validform is using the name of the field also for the id of the field but maybe that is not a correct implementation because it causes this problem. 

Maybe a solution would be to prefix the field ids with the form id. So you get field ids 'FormA_required' and 'FormB_required'.

**Comment by rvanbaalen** [comment]
VFB is indeed using names and IDs interchangeable. Knowing this, a dev who uses VFB can simply use unique form names (by prefixing the names) to prevent such errors. 

It would indeed be considerable to automatically prefix form fields with the form name to enforce more unique element naming.

Perhaps @flangfeldt can share his two cents on this matter. For now I'm labeling this low priority as this can be easily prevented by using unique naming conventions yourself if you're using multiple forms on one page.

**Comment by flangfeldt** [comment]
I agree that it would be a little easier if we would ONLY work with the field names and not the ids at all. This is a legacy topic, in ye old days it was much quicker to select a HTML element by id instead of name.

As Robin is pointing out, this is not really an issue. You, as a developer, have full control over the naming of field ids. Don't give fields the same name and you are good to go.

Indeed very low priority, something we would address in a major rewrite.
